### ISSUE TITLE
被BAN了？

### ISSUE THREAD

**Issue by Shiraha-cloud** [chh-yu/GlaDOS-auto-checkin#2]
token 变了？

**Comment by xRosemary** [comment]
token变了，请求方式也需要重写，我目前把这个改好了，在pr里面，目前还没合并，等等吧 @Shiraha-cloud

**Comment by Shiraha-cloud** [comment]
> token变了，请求方式也需要重写，我目前把这个改好了，在pr里面，目前还没合并，等等吧 @Shiraha-cloud 

嗯嗯，用了这个好久，蛮好的，非常感谢

**Comment by Shiraha-cloud** [comment]
> 
可以使用，感谢~
